name: Run Test Cases for Basic Calculator Operations

on:
  schedule:
    # Run every day at midnight UTC
    - cron: '0 3 * * *' 
  push:
    branches:
      - master # Run tests on push to the master branch
      - feature/* # Run tests on feature branches
  pull_request:
    branches:
      - master # Run tests on pull requests to the master branch
  workflow_dispatch:
    inputs:
      test-script:
        description: 'Test script to run'
        required: true
        default: 'divisionTests' # Default test script if no input is provided
        options:
          - divisionTests
          - otherTests
          - validationTests
          - allTests

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use Node.js version 16
          cache: 'npm' # Cache npm modules for faster builds

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci # Clean install dependencies from package-lock.json

      # Step 4: Run tests
      - name: Run Tests
        run: npm run ${{ github.event.inputs.test-script }}

      # Step 5: Archive Test Results
      - name: Archive Test Results
        if: always() 
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: cypress/reports/
          retention-days: 30 
